name: ground_break
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

  ffmpeg_kit_flutter: ^5.1.0
  websafe_svg: ^3.0.0+3
  image_picker: ^0.8.7
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  video_player: ^2.6.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.7
  share_plus: ^6.3.1
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0

  cloud_firestore: ^4.4.5
  cloud_functions: ^4.0.13
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  firebase_dynamic_links: ^5.0.17

  equatable: ^2.0.5
  http: ^0.13.5

  syncfusion_flutter_gauges: ^21.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

dependency_overrides:
  intl: ^0.18.0
  collection: ^1.17.1
  path: ^1.8.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/templates/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
